### ISSUE TITLE
Add Comments to the theme/blog posts.

### ISSUE THREAD

**Issue by Belliusz** [zkSNACKs/WasabiBlog#3]
Our subscribers cannot comment on any posts.

**Comment by davterra** [comment]
Having administered a few blogs over the years, my opinion is to think long and hard over whether you want to enable comments, and if you decide to do it, first have a plan in place as to who will curate it and reply to the comments. I think Google might throw a little more SEO credit to a site that engages with its users, but I've never been able to discern if that is worth the tremendous amount of time and work in managing the process. And, enabling comments without responding is a bad look.

**Comment by Belliusz** [comment]
This is good advice. I'll bring this up when we continue our discussion on the framework and administration of the blog.

**Comment by davterra** [comment]
You can provide links to the Wasabi Telegram channel if people want to comment. I think it would be nice, if there is a plug-in or extension available (I'm a long-time Wordpress guy) that would allow people to click/applaud like you can at the bottom of Medium articles, it would be a nice indicator of what content is favored / not favored. More reliable info than just tracking traffic, I think,

**Comment by Belliusz** [comment]
I like the idea, but I'm concerned with feasibility using the fizzy theme. I don't want to overburden David with this if the feature is not easily supported.

**Comment by nopara73** [comment]
I think the blog itself is a large enough maintenance burden without comments. Lately comments are delegated to social media where the content is shared.

**Comment by Belliusz** [comment]
So let's agree then that we will not install comments, but if we can just put a rating thing at the bottom of each post (like Medium), then that would be best. In the end, though, this is a very low priority.

**Comment by nopara73** [comment]
Oh, the other (blocker) issue here is that we should not have comments, nor rating system as that'd require user data collection, which we don't do.
