### ISSUE TITLE
Increase the Number of Posts Per Page to 20 (or more)

### ISSUE THREAD

**Issue by Belliusz** [zkSNACKs/WasabiBlog#4]
It would be best if the user didn't have to click on a button to see the next 5 posts. Ideally, if they just continue scrolling down to see older posts, that's best. Otherwise, if there were a simple button to "see more" or "more posts" that would then load the next 10 or 20 posts. This is the ideal because people don't want to click onto a new page and scrolling down for more is how Facebook has programmed us to behave online.

**Comment by molnard** [comment]
Fixed: https://github.com/zkSNACKs/WasabiBlog/commit/4e6a56c1549257e6120ddbdf2bab240d360524e3

**Comment by molnard** [comment]
modified
