### ISSUE TITLE
Add the Sliding Carousel and Featured Posts Highlight.

### ISSUE THREAD

**Issue by Belliusz** [zkSNACKs/WasabiBlog#5]
Riccardo and I like the sliding carousel and the featured posts highlight thing on the right. Can we add this to make our blog more snazzy?

**Comment by molnard** [comment]
For now, this seems to be unnecessary. Maybe if there will be more posts. Let's keep this issues open for later discussion.

**Comment by molnard** [comment]
@Belliusz with the @ character you can tag ppl so they will see notifications. Like @RiccardoMasutti

**Comment by molnard** [comment]
The blog looks nice now, I don't think we need this. Closing. Feel free to reopen if there is a reason to implement this.
