### ISSUE TITLE
Add Bitcoin price tab with the calculator button.

### ISSUE THREAD

**Issue by ghost** [zkSNACKs/WasabiBlog#7]
If you click to that
![image](https://user-images.githubusercontent.com/68002187/86899938-f277e980-c10a-11ea-94ff-48046de0316c.png)
This tab will appear.
![image](https://user-images.githubusercontent.com/68002187/86896741-bb073e00-c106-11ea-8715-4d6044914ef5.png)
And if you click to the calculator, you can calculate how much do you want to buy, for example.
![image](https://user-images.githubusercontent.com/68002187/86896801-d5d9b280-c106-11ea-83c8-c9df451d4109.png)
Something like that i think is a good idea, but with another design

**Comment by molnard** [comment]
Hi there,

Thank you for your contribution and welcome here. I don't see the point of having this in a blog. Ppl are not buying or selling BTC here. Showing a diagram could be interesting but still not for the blog.

**Comment by ghost** [comment]
Concept NACK, for the reasons @molnard mentioned, it's a blog, not an exchange.
